@startuml
skinparam backgroundColor #EEEBDC
skinparam handwritten true
skinparam sequenceMessageAlign center
autonumber

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DeepSkyBlue
ParticipantBackgroundColor DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor #A9DCDF

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}

server1 ->(40) server2++: SYN
destroy server2
server2 -->(40) server1--: SYN+ASK
note right #FFAAAA : 3-way handshake가 끝나기 전에 네트워크 에러가 발생이 되면 \n ConnectionTimeout 이 발생이 된다.
destroy server2
server1 --->(40) server2++: ASK
destroy server2
@enduml
